# Generated by Django 4.2.6 on 2024-03-26 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usercreaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usercreaterequest',
            options={'verbose_name': 'Запрос на регистрацию', 'verbose_name_plural': 'Запросы на регистрацию'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.AddField(
            model_name='user',
            name='user_documents',
            field=models.ManyToManyField(blank=True, default=None, to='users.document', verbose_name='Документы'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.type'),
        ),
    ]
