# Generated by Django 4.2.6 on 2024-04-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='score',
        ),
        migrations.AddField(
            model_name='type',
            name='score',
            field=models.IntegerField(default=0, help_text="Score based on the document's importance."),
        ),
    ]
