# Generated by Django 4.2.6 on 2024-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_document_score_type_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_documents',
            field=models.ManyToManyField(blank=True, default=[], to='users.document', verbose_name='Документы'),
        ),
    ]
