# Generated by Django 4.2.6 on 2024-04-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_user_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
