# Generated by Django 4.2.6 on 2024-04-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_type_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apppy_approved',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
