# Generated by Django 4.2.6 on 2024-04-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_apppy_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apppy_approved',
            new_name='apply_approved',
        ),
    ]
