# Generated by Django 4.2.6 on 2024-05-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_apppy_approved_user_apply_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='decline_reason',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
