# Generated by Django 4.2.6 on 2024-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_university_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='distance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
