# Generated by Django 4.2.6 on 2024-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
