# Generated by Django 4.2.6 on 2024-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_university_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
