# Generated by Django 4.2.6 on 2024-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_university_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
