# Generated by Django 4.2.6 on 2024-05-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='decline_reason',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.university', verbose_name='Универ'),
        ),
    ]
