# Generated by Django 4.2.6 on 2024-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_document_decline_reason_alter_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место в общаге'),
        ),
    ]
