# Generated by Django 4.2.6 on 2024-05-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
