# Generated by Django 4.2.6 on 2024-05-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_university_phone_number_university_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='university',
            name='title',
        ),
    ]
