# Generated by Django 4.2.6 on 2024-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='document_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
